title: Transmute Vocabulary
description: Mapping cyber security terminology use related to NIST, W3C, IETF, Decentralized Identifiers and Verifiable Credentials
# google_analytics: [Your Google Analytics tracking ID]